version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: pg_local_dev
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  application:
    image: otus-highload-study:homework1
    container_name: otus_highload_study
    environment:
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "8080:8080"

#docker-compose -f ./.docker-compose/local-demo/docker-compose.yml up -d
#docker-compose -f ./.docker-compose/local-demo/docker-compose.yml down