version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: pg_local_dev
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"